version: '2'

services:
  timer:
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: .
      # Имя Docker-файла из которого будет собран образ
      dockerfile: dockerfile
      # Команда, которая будет выполнена после старта сервиса  
    command: bash app/data/example4.bash
    volumes:
      - "/home/den/shared:/app/data"
    environment:
      TZ: "Europe/Moscow" 

  # volumes: 
  #  myvolume:


 # listener:
  #  image: osrf/ros:humble-desktop
   # command: ros2 run demo_nodes_cpp listener
   # depends_on:
    #  - talker
